import os
import sys
from typing import List, Dict
from urllib.parse import urlparse, unquote
import ssl
from pathlib import Path

from dotenv import load_dotenv

DEPS_DIR = Path(__file__).resolve().parent / ".deps"
if DEPS_DIR.exists() and str(DEPS_DIR) not in sys.path:
    sys.path.insert(0, str(DEPS_DIR))

import pg8000.dbapi as pg8000

load_dotenv()

DB_URL = os.getenv("SUPABASE_DB_URL") or os.getenv("DATABASE_URL")

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'TODO' CHECK (status IN ('TODO', 'PARTIAL', 'DONE', 'ROADMAP')),
    category TEXT DEFAULT 'General',
    description TEXT DEFAULT '',
    priority TEXT NOT NULL DEFAULT 'Medium' CHECK (priority IN ('Low', 'Medium', 'High', 'Critical')),
    assignee TEXT DEFAULT '',
    due_date DATE NULL,
    tags TEXT[] NOT NULL DEFAULT '{}'::text[],
    progress INTEGER NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_items_status ON items (status);
CREATE INDEX IF NOT EXISTS idx_items_category ON items (category);
CREATE INDEX IF NOT EXISTS idx_items_priority ON items (priority);
CREATE INDEX IF NOT EXISTS idx_items_created_at ON items (created_at DESC);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'items'
          AND column_name = 'tags'
          AND data_type = 'text'
    ) THEN
        ALTER TABLE public.items
        ALTER COLUMN tags TYPE TEXT[]
        USING CASE
            WHEN tags IS NULL OR btrim(tags) = '' THEN '{}'::text[]
            ELSE regexp_split_to_array(tags, '\\s*,\\s*')
        END;
    END IF;
END $$;
"""

ALLOWED_UPDATE_COLUMNS = [
    "title",
    "status",
    "category",
    "description",
    "priority",
    "assignee",
    "due_date",
    "tags",
    "progress",
]


def _normalize_tags(value):
    if value is None:
        return []
    if isinstance(value, list):
        return [str(v).strip() for v in value if str(v).strip()]
    if isinstance(value, str):
        return [v.strip() for v in value.split(",") if v.strip()]
    return []


def _get_conn():
    if not DB_URL:
        raise ValueError("Set SUPABASE_DB_URL (or DATABASE_URL) in .env")
    parsed = urlparse(DB_URL)
    if parsed.scheme not in ("postgresql", "postgres"):
        raise ValueError("SUPABASE_DB_URL must start with postgresql://")

    # Python 3.8 on Windows can fail certificate-chain validation with Supabase pooler.
    # Use non-verifying TLS context for local development compatibility.
    return pg8000.connect(
        user=unquote(parsed.username or ""),
        password=unquote(parsed.password or ""),
        host=parsed.hostname,
        port=parsed.port or 5432,
        database=(parsed.path or "/postgres").lstrip("/"),
        ssl_context=ssl._create_unverified_context(),
    )


def _rows_to_dicts(cursor, rows):
    columns = [desc[0] for desc in cursor.description] if cursor.description else []
    return [dict(zip(columns, row)) for row in rows]


def init_db():
    with _get_conn() as conn:
        cursor = conn.cursor()
        try:
            cursor.execute(SCHEMA_SQL)
        finally:
            cursor.close()
        conn.commit()


def get_all_items() -> List[Dict]:
    with _get_conn() as conn:
        cursor = conn.cursor()
        try:
            cursor.execute("SELECT * FROM items ORDER BY id ASC")
            rows = cursor.fetchall()
            return _rows_to_dicts(cursor, rows)
        finally:
            cursor.close()


def clear_all_items():
    with _get_conn() as conn:
        cursor = conn.cursor()
        try:
            cursor.execute("DELETE FROM items")
        finally:
            cursor.close()
        conn.commit()


def add_item_and_return(data: Dict) -> Dict:
    with _get_conn() as conn:
        cursor = conn.cursor()
        try:
            cursor.execute(
                """
                INSERT INTO items (title, status, category, description, priority, assignee, due_date, tags, progress)
                VALUES (%s, %s, %s, %s, %s, %s, NULLIF(%s, '')::date, %s, %s)
                RETURNING *
                """,
                (
                    data.get("title"),
                    data.get("status", "TODO"),
                    data.get("category", "General"),
                    data.get("description", ""),
                    data.get("priority", "Medium"),
                    data.get("assignee", ""),
                    data.get("due_date", ""),
                    _normalize_tags(data.get("tags")),
                    data.get("progress", 0),
                ),
            )
            row = cursor.fetchone()
            columns = [desc[0] for desc in cursor.description] if cursor.description else []
        finally:
            cursor.close()
        conn.commit()
        if not row:
            return {}
        return dict(zip(columns, row))


def execute_operations(operations: List[Dict]):
    with _get_conn() as conn:
        cursor = conn.cursor()
        try:
            for op in operations:
                action = op.get("action")
                if action == "add":
                    cursor.execute(
                        """
                        INSERT INTO items (title, status, category, description, priority, assignee, due_date, tags, progress)
                        VALUES (%s, %s, %s, %s, %s, %s, NULLIF(%s, '')::date, %s, %s)
                        """,
                        (
                            op.get("title"),
                            op.get("status", "TODO"),
                            op.get("category", "General"),
                            op.get("description", ""),
                            op.get("priority", "Medium"),
                            op.get("assignee", ""),
                            op.get("due_date", ""),
                            _normalize_tags(op.get("tags")),
                            op.get("progress", 0),
                        ),
                    )
                elif action == "update":
                    fields = []
                    values = []
                    for col in ALLOWED_UPDATE_COLUMNS:
                        if col in op:
                            if col == "due_date":
                                fields.append(f"{col} = NULLIF(%s, '')::date")
                            elif col == "tags":
                                fields.append(f"{col} = %s")
                                values.append(_normalize_tags(op[col]))
                                continue
                            else:
                                fields.append(f"{col} = %s")
                            values.append(op[col])

                    if fields and "id" in op:
                        query = f"UPDATE items SET {', '.join(fields)} WHERE id = %s"
                        values.append(op["id"])
                        cursor.execute(query, values)
                elif action == "delete":
                    if "id" in op:
                        cursor.execute("DELETE FROM items WHERE id = %s", (op["id"],))
        finally:
            cursor.close()
        conn.commit()
