-- Project OS Bot schema for Supabase Postgres
-- Paste and run in Supabase SQL Editor.

create table if not exists public.items (
    id bigint generated by default as identity primary key,
    title text not null,
    status text not null default 'TODO'
        check (status in ('TODO', 'PARTIAL', 'DONE', 'ROADMAP')),
    category text default 'General',
    description text default '',
    priority text not null default 'Medium'
        check (priority in ('Low', 'Medium', 'High', 'Critical')),
    assignee text default '',
    due_date date null,
    tags text[] not null default '{}'::text[],
    progress integer not null default 0
        check (progress >= 0 and progress <= 100),
    created_at timestamptz not null default now()
);

create index if not exists idx_items_status on public.items (status);
create index if not exists idx_items_category on public.items (category);
create index if not exists idx_items_priority on public.items (priority);
create index if not exists idx_items_created_at on public.items (created_at desc);

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'items'
          and column_name = 'tags'
          and data_type = 'text'
    ) then
        alter table public.items
        alter column tags type text[]
        using case
            when tags is null or btrim(tags) = '' then '{}'::text[]
            else regexp_split_to_array(tags, '\s*,\s*')
        end;
    end if;
end $$;

-- Optional Row Level Security template:
-- alter table public.items enable row level security;
-- create policy "Allow all for service role" on public.items
--   for all to service_role using (true) with check (true);
